[package]
name = "synth-tracker"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
eframe = "0.29.1"
cpal = "0.15.3"
fundsp = { git = "https://github.com/SamiPerttu/fundsp.git", default-features = false, features = ["std"] }
midir = "0.10.0"
serde = { version = "1.0.214", features = ["derive"] }
toml = "0.8.19"
rand = "0.8.5"

[profile.dev]
opt-level = 1