[package]
name = "synth-tracker"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
eframe = "0.29.1"
cpal = "0.15.3"
fundsp = { version = "0.20.0", default-features = false, features = ["std"] }
midir = "0.10.0"
anyhow = "1.0.92"
serde = { version = "1.0.214", features = ["derive"] }
toml = "0.8.19"

[profile.dev]
opt-level = 1