[package]
name = "synth-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
cpal = "0.15.3"
fundsp = { version = "0.20.0", default-features = false, features = ["std"] }
midir = "0.10.0"
anyhow = "1.0.92"