name: Build

# Run only when a new tag is pushed.
on:
  push:
    tags:
    - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt install libasound2-dev libjack-jackd2-dev libwayland-dev
    - name: Build
      run: cargo build --release
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux
        path: target/release/osctet

  build-windows:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows
        path: target/release/osctet.exe

  build-macos:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Bundle
      run: mv target/release/osctet macos/Osctet.app/Contents/MacOS/osctet
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos
        path: macos/