name: Build

# Run only when a new tag is pushed.
on:
  push:
    tags:
    - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt install libasound2-dev libjack-jackd2-dev libwayland-dev libdbus-1-dev
    - name: Build
      run: cargo build --release
    - run: mv target/release/osctet .
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-x86_64
        path: |
          osctet
          demosongs/

  build-windows:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - run: mv target/release/osctet.exe .
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-x86_64
        path: |
          osctet.exe
          demosongs/

  build-macos:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - run: mv target/release/osctet .
    # - name: Bundle
    #   run: |
    #     mkdir macos/Osctet.app/Contents/MacOS
    #     mv target/release/osctet macos/Osctet.app/Contents/MacOS/osctet
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-x86_64
        path: |
          osctet
          demosongs/

  build-macos-aarch:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - run: mv target/release/osctet .
    # - name: Bundle
    #   run: |
    #     mkdir macos/Osctet.app/Contents/MacOS
    #     mv target/release/osctet macos/Osctet.app/Contents/MacOS/osctet
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-aarch64
        path: |
          osctet
          demosongs/